### ISSUE TITLE
Question text.description == 10

### ISSUE THREAD

**Issue by juanBL** [vmtram/recognize-license-plate#3]
Hi,

I have a question, in https://github.com/vmtram/recognize-license-plate/blob/master/recognize_license_plate.py#L50 description of the text == 10? Where can I find documentation about this?

What does the constant 10 mean?

Thank you!

**Comment by juanBL** [comment]
I don't see the len ....

**Comment by tramvm** [comment]
> I don't see the len ....

this is Vietnam LN length.
